name: CI/CD HTML test

on:
  push:
    branches: [ main ]  

jobs:

  build:  # build構建
    runs-on: ubuntu-latest
    steps:
      - name: 檢出程式碼
        uses: actions/checkout@v4

      - name: 安裝相依套件 (Dependency Management)
        run: npm install
        
      - name: 編譯與建置 (Compile & build)
        run: npm run build

      - name: 上傳打包產物  (Packaging)
        uses: actions/upload-artifact@v4
        with:
          name: my-build-files
          path: dist/

# Test測試 
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 安裝相依套件
        run: npm install

      - name: 下載打包產物
        uses: actions/download-artifact@v4
        with:
          name: my-build-files
          path: dist/

      - name: 執行自動化測試
        run: npm test   


  # deploy部署階段 
  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: 下載打包產物
        uses: actions/download-artifact@v4
        with:
          name: my-build-files
          path: dist/

      - name: 部署到 GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
